apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: debug
    logFormat: pretty
    metricsNamePrefix: event_exporter_
    receivers:
      - name: "dump"
        file:
          path: "/dev/stdout"
          layout: {}
      - name: "victorialogs"
        loki:
          url: "http://172.16.66.106:9428/insert/loki/api/v1/push"
          streamLabels:
            source: kubernetes-event-exporter
    route:
      routes:
        - match:
            - receiver: "dump"
            - receiver: "victorialogs"
